<?php
// image-layout-to-gutenberg/includes/mock-ai-analyzer.php

if ( ! defined( "WPINC" ) ) {
    die;
}

// Ensure the interface is available.
// Should already be included by the main plugin file, but good practice for standalone usability.
// include_once __DIR__ . "/ai-analyzer-interface.php"; // Using __DIR__ for robustness

class MockAIAnalyzer implements ImageLayoutAIAnalyzerInterface {

    /**
     * Simulates analyzing an image and returns a hardcoded structured representation.
     *
     * @param int $image_id The WordPress attachment ID of the image to analyze.
     *                      In this mock version, we might use it to vary the response.
     * @return array An array of associative arrays representing Gutenberg blocks.
     * @throws Exception If the analysis simulation encounters a predefined error.
     */
    public function analyzeImage(int $image_id): array {
        // Simulate different layouts based on image ID or other factors
        // For simplicity, let's return one of a few predefined layouts.
        // In a real scenario, you might fetch image metadata or even analyze the image name if $image_id is a placeholder.

        if ($image_id % 2 === 0) { // Even image ID - Layout 1
            return [
                [
                    "type" => "core/heading",
                    "attributes" => [
                        "level" => 1,
                        "content" => __("Mocked Header from Image", "image-layout-to-gutenberg") . " (ID: $image_id)"
                    ]
                ],
                [
                    "type" => "core/paragraph",
                    "attributes" => [
                        "content" => __("This is a paragraph generated by the mock AI service based on the uploaded image. It's a simple text block.", "image-layout-to-gutenberg")
                    ]
                ],
                [
                    "type" => "core/image",
                    "attributes" => [
                        "id" => $image_id, // Use the provided image ID for the mock image block
                        "url" => wp_get_attachment_url($image_id) ?: "https://via.placeholder.com/600x400.png?text=Uploaded+Image+" . $image_id,
                        "alt" => __("Mocked image based on upload", "image-layout-to-gutenberg"),
                        "caption" => __("This is the uploaded image (ID: $image_id)", "image-layout-to-gutenberg"),
                        "align" => "center"
                    ]
                ]
            ];
        } else { // Odd image ID - Layout 2
            return [
                [
                    "type" => "core/columns",
                    "attributes" => [
                        // No specific attributes for core/columns itself usually
                    ],
                    "innerBlocks" => [
                        [ // First column
                            "type" => "core/column",
                            "attributes" => [],
                            "innerBlocks" => [
                                [
                                    "type" => "core/heading",
                                    "attributes" => [
                                        "level" => 2,
                                        "content" => __("Column 1 Heading", "image-layout-to-gutenberg")
                                    ]
                                ],
                                [
                                    "type" => "core/paragraph",
                                    "attributes" => [
                                        "content" => __("Some text content for the first column. This mock service is simulating a multi-column layout.", "image-layout-to-gutenberg")
                                    ]
                                ]
                            ]
                        ],
                        [ // Second column
                            "type" => "core/column",
                            "attributes" => [],
                            "innerBlocks" => [
                                [
                                    "type" => "core/paragraph",
                                    "attributes" => [
                                        "content" => __("This is the second column. It might contain different types of blocks.", "image-layout-to-gutenberg")
                                    ]
                                ],
                                [
                                    "type" => "core/image",
                                    "attributes" => [
                                        // In a real case, the AI would detect another image or use a placeholder
                                        "url" => "https://via.placeholder.com/300x200.png?text=Placeholder+Col+2",
                                        "alt" => __("Placeholder image in column 2", "image-layout-to-gutenberg"),
                                        "align" => "left"
                                    ]
                                ]
                            ]
                        ]
                    ]
                ],
                [
                    "type" => "core/paragraph",
                    "attributes" => [
                        "content" => __("This paragraph appears after the two-column layout, demonstrating a mixed structure.", "image-layout-to-gutenberg")
                    ]
                ]
            ];
        }
    }
}
